# TODO place this in a resources folder somewhere
# Fill in and change name to config.toml to use. alternatively use environment variables

google_ads_account_id = 0
google_developer_token = ""
google_ads_endpoint = ""
google_oauth2_client_id = ""
google_oauth2_client_secret = ""
google_redirect_url = ""
google_oauth2_scope = ""
google_initial_token = ""

database_type = ""
database_username = ""
database_name = ""
database_ssl_mode = ""

taboola_backstage_endpoint = ""
taboola_oauth2_client_id = ""
taboola_oauth2_client_secret = ""
taboola_redirect_url = ""
taboola_oauth2_scope = ""
taboola_oauth2_token = ""
taboola_oauth2_auth_url= ""
taboola_oauth2_token_url = ""
taboola_oauth2_username = ""
taboola_oauth2_password = ""